/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorieProdusAudienceCategorieRouteImport } from './routes/categorie-produs.$audience.$categorie'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieProdusAudienceCategorieRoute =
  CategorieProdusAudienceCategorieRouteImport.update({
    id: '/categorie-produs/$audience/$categorie',
    path: '/categorie-produs/$audience/$categorie',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorie-produs/$audience/$categorie': typeof CategorieProdusAudienceCategorieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorie-produs/$audience/$categorie': typeof CategorieProdusAudienceCategorieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorie-produs/$audience/$categorie': typeof CategorieProdusAudienceCategorieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categorie-produs/$audience/$categorie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categorie-produs/$audience/$categorie'
  id: '__root__' | '/' | '/categorie-produs/$audience/$categorie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategorieProdusAudienceCategorieRoute: typeof CategorieProdusAudienceCategorieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie-produs/$audience/$categorie': {
      id: '/categorie-produs/$audience/$categorie'
      path: '/categorie-produs/$audience/$categorie'
      fullPath: '/categorie-produs/$audience/$categorie'
      preLoaderRoute: typeof CategorieProdusAudienceCategorieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategorieProdusAudienceCategorieRoute: CategorieProdusAudienceCategorieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
